fragment PagesParts on Pages {
  __typename
  heroEyebrow
  heroHeadline
  heroSubheadline
  heroCtaLabel
  heroCtaHref
  heroImage
  currentJourneyEyebrow
  currentJourneyHeadline
  currentJourneyBody
  currentJourneyBody2
  currentJourneyCtaLabel
  currentJourneyCtaHref
  currentJourneyImage
  episodesEyebrow
  episodesHeadline
  destinationsEyebrow
  destinationsHeadline
  europeEyebrow
  europeHeadline
  europeSubtext
  europeCtaLabel
  europeCtaHref
  hacksEyebrow
  hacksHeadline
  hacksSubtext
  emailHeadline
  emailSubheadline
  journalEyebrow
  journalHeadline
  originEyebrow
  originHeadline
  originParagraph1
  originParagraph2
  originParagraph3
  originParagraph4
  familyEyebrow
  familyHeadline
  familyImage
  dadBio
  momBio
  olderKidBio
  youngerKidBio
  approachEyebrow
  approachHeadline
  approachBody
  overviewEyebrow
  overviewHeadline
  overviewParagraph1
  overviewParagraph2
  overviewParagraph3
  episodesSubtext
}

fragment SettingsParts on Settings {
  __typename
  siteName
  siteTagline
  youtube
  instagram
  facebook
  email
  footerCopyright
}

fragment EuropeEpisodesParts on EuropeEpisodes {
  __typename
  title
  country
  flag
  episode
  duration
  image
  heroImage
  description
  summary
  storyText
  comingSoonText
  chaosMoment
  highlights
  itinerary {
    __typename
    day
    title
    description
  }
  familyTips
  budget {
    __typename
    item
    cost
    perDay
  }
  photos
  youtubeId
  body
}

fragment UkEpisodesParts on UkEpisodes {
  __typename
  title
  country
  flag
  episode
  duration
  image
  heroImage
  description
  comingSoonText
  highlights
  youtubeId
  body
}

fragment GearParts on Gear {
  __typename
  name
  category
  price
  rating
  summary
  image
  affiliateUrl
}

fragment DestinationsParts on Destinations {
  __typename
  name
  slug
  flag
  summary
  image
  episodeCount
  seriesLink
}

fragment JournalParts on Journal {
  __typename
  title
  excerpt
  date
  category
  readTime
  image
  body
}

fragment TravelHacksParts on TravelHacks {
  __typename
  title
  category
  readTime
  image
  body
}
