//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  journal: Journal;
  journalConnection: JournalConnection;
  episodes: Episodes;
  episodesConnection: EpisodesConnection;
  gear: Gear;
  gearConnection: GearConnection;
  destinations: Destinations;
  destinationsConnection: DestinationsConnection;
  travelHacks: TravelHacks;
  travelHacksConnection: TravelHacksConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryJournalArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryJournalConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<JournalFilter>;
};


export type QueryEpisodesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEpisodesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EpisodesFilter>;
};


export type QueryGearArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGearConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GearFilter>;
};


export type QueryDestinationsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDestinationsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DestinationsFilter>;
};


export type QueryTravelHacksArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTravelHacksConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TravelHacksFilter>;
};

export type DocumentFilter = {
  journal?: InputMaybe<JournalFilter>;
  episodes?: InputMaybe<EpisodesFilter>;
  gear?: InputMaybe<GearFilter>;
  destinations?: InputMaybe<DestinationsFilter>;
  travelHacks?: InputMaybe<TravelHacksFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Journal | Episodes | Gear | Destinations | TravelHacks | Folder;

export type Journal = Node & Document & {
  __typename?: 'Journal';
  title: Scalars['String']['output'];
  excerpt?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  readTime?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type JournalFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  category?: InputMaybe<StringFilter>;
  readTime?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type JournalConnectionEdges = {
  __typename?: 'JournalConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Journal>;
};

export type JournalConnection = Connection & {
  __typename?: 'JournalConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<JournalConnectionEdges>>>;
};

export type Episodes = Node & Document & {
  __typename?: 'Episodes';
  title: Scalars['String']['output'];
  country?: Maybe<Scalars['String']['output']>;
  flag?: Maybe<Scalars['String']['output']>;
  episode?: Maybe<Scalars['Float']['output']>;
  duration?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  youtubeId?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type EpisodesFilter = {
  title?: InputMaybe<StringFilter>;
  country?: InputMaybe<StringFilter>;
  flag?: InputMaybe<StringFilter>;
  episode?: InputMaybe<NumberFilter>;
  duration?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  youtubeId?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type EpisodesConnectionEdges = {
  __typename?: 'EpisodesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Episodes>;
};

export type EpisodesConnection = Connection & {
  __typename?: 'EpisodesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EpisodesConnectionEdges>>>;
};

export type Gear = Node & Document & {
  __typename?: 'Gear';
  name: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  rating?: Maybe<Scalars['String']['output']>;
  summary?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  affiliateUrl?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GearFilter = {
  name?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  rating?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  affiliateUrl?: InputMaybe<StringFilter>;
};

export type GearConnectionEdges = {
  __typename?: 'GearConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Gear>;
};

export type GearConnection = Connection & {
  __typename?: 'GearConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GearConnectionEdges>>>;
};

export type Destinations = Node & Document & {
  __typename?: 'Destinations';
  name: Scalars['String']['output'];
  flag?: Maybe<Scalars['String']['output']>;
  summary?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  episodeCount?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DestinationsFilter = {
  name?: InputMaybe<StringFilter>;
  flag?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  episodeCount?: InputMaybe<NumberFilter>;
};

export type DestinationsConnectionEdges = {
  __typename?: 'DestinationsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Destinations>;
};

export type DestinationsConnection = Connection & {
  __typename?: 'DestinationsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DestinationsConnectionEdges>>>;
};

export type TravelHacks = Node & Document & {
  __typename?: 'TravelHacks';
  title: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  readTime?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TravelHacksFilter = {
  title?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  readTime?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type TravelHacksConnectionEdges = {
  __typename?: 'TravelHacksConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<TravelHacks>;
};

export type TravelHacksConnection = Connection & {
  __typename?: 'TravelHacksConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TravelHacksConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateJournal: Journal;
  createJournal: Journal;
  updateEpisodes: Episodes;
  createEpisodes: Episodes;
  updateGear: Gear;
  createGear: Gear;
  updateDestinations: Destinations;
  createDestinations: Destinations;
  updateTravelHacks: TravelHacks;
  createTravelHacks: TravelHacks;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateJournalArgs = {
  relativePath: Scalars['String']['input'];
  params: JournalMutation;
};


export type MutationCreateJournalArgs = {
  relativePath: Scalars['String']['input'];
  params: JournalMutation;
};


export type MutationUpdateEpisodesArgs = {
  relativePath: Scalars['String']['input'];
  params: EpisodesMutation;
};


export type MutationCreateEpisodesArgs = {
  relativePath: Scalars['String']['input'];
  params: EpisodesMutation;
};


export type MutationUpdateGearArgs = {
  relativePath: Scalars['String']['input'];
  params: GearMutation;
};


export type MutationCreateGearArgs = {
  relativePath: Scalars['String']['input'];
  params: GearMutation;
};


export type MutationUpdateDestinationsArgs = {
  relativePath: Scalars['String']['input'];
  params: DestinationsMutation;
};


export type MutationCreateDestinationsArgs = {
  relativePath: Scalars['String']['input'];
  params: DestinationsMutation;
};


export type MutationUpdateTravelHacksArgs = {
  relativePath: Scalars['String']['input'];
  params: TravelHacksMutation;
};


export type MutationCreateTravelHacksArgs = {
  relativePath: Scalars['String']['input'];
  params: TravelHacksMutation;
};

export type DocumentUpdateMutation = {
  journal?: InputMaybe<JournalMutation>;
  episodes?: InputMaybe<EpisodesMutation>;
  gear?: InputMaybe<GearMutation>;
  destinations?: InputMaybe<DestinationsMutation>;
  travelHacks?: InputMaybe<TravelHacksMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  journal?: InputMaybe<JournalMutation>;
  episodes?: InputMaybe<EpisodesMutation>;
  gear?: InputMaybe<GearMutation>;
  destinations?: InputMaybe<DestinationsMutation>;
  travelHacks?: InputMaybe<TravelHacksMutation>;
};

export type JournalMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  readTime?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type EpisodesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  country?: InputMaybe<Scalars['String']['input']>;
  flag?: InputMaybe<Scalars['String']['input']>;
  episode?: InputMaybe<Scalars['Float']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  youtubeId?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type GearMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  rating?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  affiliateUrl?: InputMaybe<Scalars['String']['input']>;
};

export type DestinationsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  flag?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  episodeCount?: InputMaybe<Scalars['Float']['input']>;
};

export type TravelHacksMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  readTime?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type JournalPartsFragment = { __typename: 'Journal', title: string, excerpt?: string | null, date?: string | null, category?: string | null, readTime?: string | null, image?: string | null, body?: any | null };

export type EpisodesPartsFragment = { __typename: 'Episodes', title: string, country?: string | null, flag?: string | null, episode?: number | null, duration?: string | null, description?: string | null, image?: string | null, youtubeId?: string | null, body?: any | null };

export type GearPartsFragment = { __typename: 'Gear', name: string, category?: string | null, price?: string | null, rating?: string | null, summary?: string | null, image?: string | null, affiliateUrl?: string | null };

export type DestinationsPartsFragment = { __typename: 'Destinations', name: string, flag?: string | null, summary?: string | null, image?: string | null, episodeCount?: number | null };

export type TravelHacksPartsFragment = { __typename: 'TravelHacks', title: string, category?: string | null, readTime?: string | null, image?: string | null, body?: any | null };

export type JournalQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type JournalQuery = { __typename?: 'Query', journal: { __typename: 'Journal', id: string, title: string, excerpt?: string | null, date?: string | null, category?: string | null, readTime?: string | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type JournalConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<JournalFilter>;
}>;


export type JournalConnectionQuery = { __typename?: 'Query', journalConnection: { __typename?: 'JournalConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'JournalConnectionEdges', cursor: string, node?: { __typename: 'Journal', id: string, title: string, excerpt?: string | null, date?: string | null, category?: string | null, readTime?: string | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type EpisodesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EpisodesQuery = { __typename?: 'Query', episodes: { __typename: 'Episodes', id: string, title: string, country?: string | null, flag?: string | null, episode?: number | null, duration?: string | null, description?: string | null, image?: string | null, youtubeId?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EpisodesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EpisodesFilter>;
}>;


export type EpisodesConnectionQuery = { __typename?: 'Query', episodesConnection: { __typename?: 'EpisodesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EpisodesConnectionEdges', cursor: string, node?: { __typename: 'Episodes', id: string, title: string, country?: string | null, flag?: string | null, episode?: number | null, duration?: string | null, description?: string | null, image?: string | null, youtubeId?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GearQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GearQuery = { __typename?: 'Query', gear: { __typename: 'Gear', id: string, name: string, category?: string | null, price?: string | null, rating?: string | null, summary?: string | null, image?: string | null, affiliateUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type GearConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GearFilter>;
}>;


export type GearConnectionQuery = { __typename?: 'Query', gearConnection: { __typename?: 'GearConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GearConnectionEdges', cursor: string, node?: { __typename: 'Gear', id: string, name: string, category?: string | null, price?: string | null, rating?: string | null, summary?: string | null, image?: string | null, affiliateUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type DestinationsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DestinationsQuery = { __typename?: 'Query', destinations: { __typename: 'Destinations', id: string, name: string, flag?: string | null, summary?: string | null, image?: string | null, episodeCount?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type DestinationsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DestinationsFilter>;
}>;


export type DestinationsConnectionQuery = { __typename?: 'Query', destinationsConnection: { __typename?: 'DestinationsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DestinationsConnectionEdges', cursor: string, node?: { __typename: 'Destinations', id: string, name: string, flag?: string | null, summary?: string | null, image?: string | null, episodeCount?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TravelHacksQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TravelHacksQuery = { __typename?: 'Query', travelHacks: { __typename: 'TravelHacks', id: string, title: string, category?: string | null, readTime?: string | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TravelHacksConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TravelHacksFilter>;
}>;


export type TravelHacksConnectionQuery = { __typename?: 'Query', travelHacksConnection: { __typename?: 'TravelHacksConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TravelHacksConnectionEdges', cursor: string, node?: { __typename: 'TravelHacks', id: string, title: string, category?: string | null, readTime?: string | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const JournalPartsFragmentDoc = gql`
    fragment JournalParts on Journal {
  __typename
  title
  excerpt
  date
  category
  readTime
  image
  body
}
    `;
export const EpisodesPartsFragmentDoc = gql`
    fragment EpisodesParts on Episodes {
  __typename
  title
  country
  flag
  episode
  duration
  description
  image
  youtubeId
  body
}
    `;
export const GearPartsFragmentDoc = gql`
    fragment GearParts on Gear {
  __typename
  name
  category
  price
  rating
  summary
  image
  affiliateUrl
}
    `;
export const DestinationsPartsFragmentDoc = gql`
    fragment DestinationsParts on Destinations {
  __typename
  name
  flag
  summary
  image
  episodeCount
}
    `;
export const TravelHacksPartsFragmentDoc = gql`
    fragment TravelHacksParts on TravelHacks {
  __typename
  title
  category
  readTime
  image
  body
}
    `;
export const JournalDocument = gql`
    query journal($relativePath: String!) {
  journal(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...JournalParts
  }
}
    ${JournalPartsFragmentDoc}`;
export const JournalConnectionDocument = gql`
    query journalConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: JournalFilter) {
  journalConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...JournalParts
      }
    }
  }
}
    ${JournalPartsFragmentDoc}`;
export const EpisodesDocument = gql`
    query episodes($relativePath: String!) {
  episodes(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EpisodesParts
  }
}
    ${EpisodesPartsFragmentDoc}`;
export const EpisodesConnectionDocument = gql`
    query episodesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EpisodesFilter) {
  episodesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EpisodesParts
      }
    }
  }
}
    ${EpisodesPartsFragmentDoc}`;
export const GearDocument = gql`
    query gear($relativePath: String!) {
  gear(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GearParts
  }
}
    ${GearPartsFragmentDoc}`;
export const GearConnectionDocument = gql`
    query gearConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GearFilter) {
  gearConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GearParts
      }
    }
  }
}
    ${GearPartsFragmentDoc}`;
export const DestinationsDocument = gql`
    query destinations($relativePath: String!) {
  destinations(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DestinationsParts
  }
}
    ${DestinationsPartsFragmentDoc}`;
export const DestinationsConnectionDocument = gql`
    query destinationsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DestinationsFilter) {
  destinationsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DestinationsParts
      }
    }
  }
}
    ${DestinationsPartsFragmentDoc}`;
export const TravelHacksDocument = gql`
    query travelHacks($relativePath: String!) {
  travelHacks(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TravelHacksParts
  }
}
    ${TravelHacksPartsFragmentDoc}`;
export const TravelHacksConnectionDocument = gql`
    query travelHacksConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TravelHacksFilter) {
  travelHacksConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TravelHacksParts
      }
    }
  }
}
    ${TravelHacksPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      journal(variables: JournalQueryVariables, options?: C): Promise<{data: JournalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JournalQueryVariables, query: string}> {
        return requester<{data: JournalQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JournalQueryVariables, query: string}, JournalQueryVariables>(JournalDocument, variables, options);
      },
    journalConnection(variables?: JournalConnectionQueryVariables, options?: C): Promise<{data: JournalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JournalConnectionQueryVariables, query: string}> {
        return requester<{data: JournalConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JournalConnectionQueryVariables, query: string}, JournalConnectionQueryVariables>(JournalConnectionDocument, variables, options);
      },
    episodes(variables: EpisodesQueryVariables, options?: C): Promise<{data: EpisodesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EpisodesQueryVariables, query: string}> {
        return requester<{data: EpisodesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EpisodesQueryVariables, query: string}, EpisodesQueryVariables>(EpisodesDocument, variables, options);
      },
    episodesConnection(variables?: EpisodesConnectionQueryVariables, options?: C): Promise<{data: EpisodesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EpisodesConnectionQueryVariables, query: string}> {
        return requester<{data: EpisodesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EpisodesConnectionQueryVariables, query: string}, EpisodesConnectionQueryVariables>(EpisodesConnectionDocument, variables, options);
      },
    gear(variables: GearQueryVariables, options?: C): Promise<{data: GearQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GearQueryVariables, query: string}> {
        return requester<{data: GearQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GearQueryVariables, query: string}, GearQueryVariables>(GearDocument, variables, options);
      },
    gearConnection(variables?: GearConnectionQueryVariables, options?: C): Promise<{data: GearConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GearConnectionQueryVariables, query: string}> {
        return requester<{data: GearConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GearConnectionQueryVariables, query: string}, GearConnectionQueryVariables>(GearConnectionDocument, variables, options);
      },
    destinations(variables: DestinationsQueryVariables, options?: C): Promise<{data: DestinationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DestinationsQueryVariables, query: string}> {
        return requester<{data: DestinationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DestinationsQueryVariables, query: string}, DestinationsQueryVariables>(DestinationsDocument, variables, options);
      },
    destinationsConnection(variables?: DestinationsConnectionQueryVariables, options?: C): Promise<{data: DestinationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DestinationsConnectionQueryVariables, query: string}> {
        return requester<{data: DestinationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DestinationsConnectionQueryVariables, query: string}, DestinationsConnectionQueryVariables>(DestinationsConnectionDocument, variables, options);
      },
    travelHacks(variables: TravelHacksQueryVariables, options?: C): Promise<{data: TravelHacksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TravelHacksQueryVariables, query: string}> {
        return requester<{data: TravelHacksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TravelHacksQueryVariables, query: string}, TravelHacksQueryVariables>(TravelHacksDocument, variables, options);
      },
    travelHacksConnection(variables?: TravelHacksConnectionQueryVariables, options?: C): Promise<{data: TravelHacksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TravelHacksConnectionQueryVariables, query: string}> {
        return requester<{data: TravelHacksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TravelHacksConnectionQueryVariables, query: string}, TravelHacksConnectionQueryVariables>(TravelHacksConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/fa3c2638-02f0-4fd0-b1ad-ad74615afbd2/github/master",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  